function [ pairname ] = xcorrpairget( ...
    singledata_dir, component )
%XCORRPAIRGET Summary of this function goes here
%   Detailed explanation goes here

pairlist_name = 'pair';
num_component = numel(component);

pairlist = cellfun(...
    @strcat, ...
    repmat({pairlist_name}, 1, num_component), ...
    repmat({'_'}, 1, num_component), ...
    num2cell(component), ...
    'UniformOutput', false);

net_dir = dir(singledata_dir);
net_name = {net_dir([net_dir.isdir] == 1).name};
net_name = net_name(3: end);
num_net = numel(net_name);

for ii = 1: num_net    
    pairlistfile = fullfile(singledata_dir, net_name(ii), pairlist);
    pairlistID = ...
        cellfun(@fopen, pairlistfile, repmat({'r'}, 1, num_component));
    pairname = ...
        cellfun(...
        @textscan, ...
        num2cell(pairlistID), ...
        repmat({'%s'}, 1, num_component), ...
        'UniformOutput', false);
    pairname = horzcat(pairname{:});
    pairname = horzcat(pairname{:});
end
arrayfun(@fclose, pairlistID);
end